# Generated by Django 4.1.2 on 2022-11-17 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipo',
            old_name='pais',
            new_name='localidad',
        ),
    ]
